import type { TaskSnapshot } from './protocol.js';
const escape=(value:unknown)=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const activityNames:Record<string,string>={series_get_manifest:'Reading image inventory',series_read_frames:'Reading series frames',viewer_observe:'Looking at the reading view',viewer_get_state:'Checking viewer state',viewer_get_capabilities:'Checking viewer tools',viewer_set_window_level:'Adjusting window / level',viewer_jump_to_slice:'Navigating slices',series_get_metadata:'Reading technical metadata',structure_radiology_report:'Structuring report',report_draft:'Drafting report'};
export function explorationMarkup(snapshot?:TaskSnapshot, busy=false):string {
  if(!snapshot)return '';
  const running=['prepared','running'].includes(snapshot.status),series=snapshot.grant.scope.kind==='series';
  const total=snapshot.coverage.reduce((n,c)=>n+c.frameCount,0),delivered=snapshot.coverage.reduce((n,c)=>n+c.delivered.length,0),remaining=Math.max(0,total-delivered);
  const images=snapshot.actions.filter(a=>a.status==='delivered').reduce((n,a)=>n+(Array.isArray((a.result as {images?:unknown[]})?.images)?(a.result as {images:unknown[]}).images.length:0),0);
  const latest=[...snapshot.actions].reverse().find(a=>['pending','claimed','submitted','awaiting_approval'].includes(String(a.status)));
  const titles:Record<string,string>={prepared:'Preparing images',running:'Model is working',completed:series&&remaining?'Answer ready · partial series':'Answer ready',failed:'Review failed',cancelled:'Review stopped',interrupted:'Review interrupted',paused:'Review paused'};
  const detail=snapshot.status==='prepared'?'Reading the image inventory…':snapshot.status==='running'?(latest?activityNames[String(latest.name)]??String(latest.name).replaceAll('_',' '):'Reviewing images and preparing the response…'):snapshot.status==='completed'?(series&&remaining?`${remaining} frames remain. Continue to send the remaining images.`:'Image delivery confirmed. See the answer above.'):(snapshot.activity??'The request ended before an answer was completed.');
  const approvals=snapshot.actions.filter(a=>a.status==='awaiting_approval');
  return `<div class="radsysx-study-status" data-state="${escape(snapshot.status)}"><div role="status" aria-live="polite"><div class="radsysx-study-status-line"><strong>${escape(titles[snapshot.status])}</strong><span>${series?'Active series':'Reading view'}</span></div>
    <p class="radsysx-study-delivery">${series?`${delivered} of ${total||'…'} frames sent`:`${images} ${images===1?'image':'images'} sent`}</p>
    ${series&&total?`<progress value="${delivered}" max="${total}" aria-label="Series frames delivered"></progress>`:''}<p>${escape(detail)}</p></div>
    ${running?'<div class="radsysx-study-actions"><button type="button" data-action="study-stop">Stop request</button><button type="button" data-action="study-takeover">Take over viewer</button></div>':snapshot.canContinue&&series&&remaining?`<div class="radsysx-study-actions"><button type="button" data-action="study-continue"${busy?' disabled':''}>Review remaining ${remaining} frames</button></div>`:''}
    ${approvals.map(a=>`<div class="radsysx-study-proposal"><strong>Review ${escape(String(a.name).replaceAll('_',' '))}</strong><pre>${escape(JSON.stringify(a.args,null,2))}</pre><button type="button" data-action="study-approve" data-operation="${escape(a.operationId)}">Approve exact change</button><button type="button" data-action="study-deny" data-operation="${escape(a.operationId)}">Decline</button></div>`).join('')}
    ${snapshot.actions.length?`<details><summary>Viewer activity</summary>${snapshot.actions.filter(a=>a.status!=='awaiting_approval').slice(-12).map(a=>`<p>${escape(activityNames[String(a.name)]??String(a.name).replaceAll('_',' '))} · ${escape(a.status==='delivered'?'images sent':a.status==='claimed'?'working':a.status==='outcome_unknown'?'outcome unconfirmed':a.status)}</p>`).join('')}</details>`:''}</div>`;
}
